title: Al-Seerah Al-Munawwarah
email: yoyomunawwar@gmail.com
permalink: none
github_username:  munawwir

theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
exclude:
  - code/
